name: ptl test
resources:
  slots_per_trial: 1
environment:
  image:  determinedai/environments-dev:python-3.10-pytorch-2.0-deepspeed-0.10.0-smartsim
hyperparameters:
  lr: 
    type: log
    base: 10
    minval: -4
    maxval: -1
  batch_size: 256
  num_workers: 4
searcher:
  name: adaptive_asha
  metric: valid_loss_epoch
  mode: aggressive
  max_length: 8
  max_trials: 10
entrypoint: python3 -m determined.launch.torch_distributed python3 mnist_ptl.py
max_restarts: 0
